# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.2
  - PG_SUPPORTED_VERSIONS=9.3
  - PG_SUPPORTED_VERSIONS=9.4
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12

language: C
dist: trusty
sudo: required

before_install:
  # apt.postgresql.org is already configured, we just need to add devel
  - |
    DIST=trusty-pgdg
    case $PG_SUPPORTED_VERSIONS in
      1*)
      # update pgdg-source.list
      sudo sed -i -e "s/pgdg.*/pgdg-testing main $PG_SUPPORTED_VERSIONS/" /etc/apt/sources.list.d/pgdg*.list
      DIST=trusty-pgdg-testing
      ;;
    esac
  - sudo apt-get -qq update

install:
  - export DEBIAN_FRONTEND=noninteractive # suppress warnings about deprecated PostgreSQL versions
  # trusty's pg_buildext doesn't cope with PG version numbers >= 10, so upgrade that to -pgdg
  - sudo apt-get install postgresql-server-dev-$PG_SUPPORTED_VERSIONS postgresql-server-dev-all/$DIST
  # install PostgreSQL $PG_SUPPORTED_VERSIONS if not there yet
  - |
    if [ ! -x /usr/lib/postgresql/$PG_SUPPORTED_VERSIONS/bin/postgres ]; then
      sudo apt-get remove --purge -y postgresql-common
      sudo apt-get install postgresql-$PG_SUPPORTED_VERSIONS
    fi
  - dpkg -l postgresql\* | cat
  - pg_lsclusters

script:
  - export PG_CONFIG=/usr/lib/postgresql/$PG_SUPPORTED_VERSIONS/bin/pg_config
  - make
  - sudo make install
  - make installcheck
